#include "discrete_output_app.h"

enum enDiscrOutput
{
	POW_OUTPUT_1_BIT=0,
	POW_OUTPUT_2_BIT,
	POW_OUTPUT_3_BIT,
	POW_OUTPUT_4_BIT,
	HL11_BIT,
	HL12_BIT,
	HL21_BIT,
	HL22_BIT,
	BUTTON_HIGHLIGHT_BIT,
	ALARM_INDICATOR_BIT,
};

#define POW_OUTPUT_1_PORT GPIOF
#define POW_OUTPUT_1_PIN	GPIO_PIN_11

#define POW_OUTPUT_2_PORT GPIOF
#define POW_OUTPUT_2_PIN	GPIO_PIN_12

#define POW_OUTPUT_3_PORT GPIOE
#define POW_OUTPUT_3_PIN	GPIO_PIN_7

#define POW_OUTPUT_4_PORT GPIOE
#define POW_OUTPUT_4_PIN	GPIO_PIN_8

#define HL11_PORT GPIOE
#define HL11_PIN	GPIO_PIN_12

#define HL12_PORT GPIOE
#define HL12_PIN	GPIO_PIN_13

#define HL21_PORT GPIOE
#define HL21_PIN	GPIO_PIN_14

#define HL22_PORT GPIOE
#define HL22_PIN	GPIO_PIN_15

#define BUTTON_HIGHLIGHT_PORT GPIOB
#define BUTTON_HIGHLIGHT_PIN	GPIO_PIN_0

#define ALARM_INDICATOR_PORT	GPIOG
#define ALARM_INDICATOR_PIN		GPIO_PIN_2



void DiscreteOutputs_SetState(uint16_t outputs)
{
		HAL_GPIO_WritePin(POW_OUTPUT_1_PORT,	POW_OUTPUT_1_PIN,	outputs&(1<<POW_OUTPUT_1_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_2_PORT,	POW_OUTPUT_2_PIN,	outputs&(1<<POW_OUTPUT_2_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_3_PORT,	POW_OUTPUT_3_PIN,	outputs&(1<<POW_OUTPUT_3_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_4_PORT,	POW_OUTPUT_4_PIN,	outputs&(1<<POW_OUTPUT_4_BIT));
	
		HAL_GPIO_WritePin(HL11_PORT,	HL11_PIN,	outputs&(1<<HL11_BIT));
		HAL_GPIO_WritePin(HL12_PORT,	HL12_PIN,	outputs&(1<<HL12_BIT));
		HAL_GPIO_WritePin(HL21_PORT,	HL21_PIN,	outputs&(1<<HL21_BIT));
		HAL_GPIO_WritePin(HL21_PORT,	HL22_PIN,	outputs&(1<<HL22_BIT));
	
	
		HAL_GPIO_WritePin(BUTTON_HIGHLIGHT_PORT,	BUTTON_HIGHLIGHT_PIN,	outputs&(1<<BUTTON_HIGHLIGHT_BIT));
		HAL_GPIO_WritePin(ALARM_INDICATOR_PORT,	ALARM_INDICATOR_PIN,	outputs&(1<<ALARM_INDICATOR_BIT));
}