#include "discrete_output_app.h"

enum enDiscrOutput
{
	POW_OUTPUT_1_BIT=0,
	POW_OUTPUT_2_BIT,
	POW_OUTPUT_3_BIT,
	POW_OUTPUT_4_BIT,
	BUTTON_HIGHLIGHT_BIT,
};

#define POW_OUTPUT_1_PORT GPIOF
#define POW_OUTPUT_1_PIN	GPIO_PIN_11

#define POW_OUTPUT_2_PORT GPIOF
#define POW_OUTPUT_2_PIN	GPIO_PIN_12

#define POW_OUTPUT_3_PORT GPIOE
#define POW_OUTPUT_3_PIN	GPIO_PIN_7

#define POW_OUTPUT_4_PORT GPIOE
#define POW_OUTPUT_4_PIN	GPIO_PIN_8

#define BUTTON_HIGHLIGHT_PORT GPIOB
#define BUTTON_HIGHLIGHT_PIN	GPIO_PIN_0

void DiscreteOutputs_SetState(uint8_t outputs)
{
		HAL_GPIO_WritePin(POW_OUTPUT_1_PORT,	POW_OUTPUT_1_PIN,	outputs&(1<<POW_OUTPUT_1_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_2_PORT,	POW_OUTPUT_2_PIN,	outputs&(1<<POW_OUTPUT_2_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_3_PORT,	POW_OUTPUT_3_PIN,	outputs&(1<<POW_OUTPUT_3_BIT));
		HAL_GPIO_WritePin(POW_OUTPUT_4_PORT,	POW_OUTPUT_4_PIN,	outputs&(1<<POW_OUTPUT_4_BIT));
		HAL_GPIO_WritePin(BUTTON_HIGHLIGHT_PORT,	BUTTON_HIGHLIGHT_PIN,	outputs&(1<<BUTTON_HIGHLIGHT_BIT));
}